title: learn code leisurely
author: Barnette
email: 1258250783@qq.com
description: > # this means to ignore newlines until "baseurl:"
 just a new coder,and want to be a professional coder

# social links
twitter_username: I do not have a twitter account # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/Barnette-ao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
